// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/sku.proto

// Protobuf Java Version: 3.25.3
package com.example.wechatmerchant.skurpc;

public interface CommonRspOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sku.CommonRsp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 code = 1;</code>
   * @return The code.
   */
  long getCode();

  /**
   * <code>string msg = 2;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 2;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
