// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/sku.proto

package com.example.wechatmerchant.skurpc;

/**
 * Protobuf type {@code sku.CreateOrUpdateItemInfoReq}
 */
public final class CreateOrUpdateItemInfoReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:sku.CreateOrUpdateItemInfoReq)
    CreateOrUpdateItemInfoReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateOrUpdateItemInfoReq.newBuilder() to construct.
  private CreateOrUpdateItemInfoReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateOrUpdateItemInfoReq() {
    itemName_ = "";
    categoryNam_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateOrUpdateItemInfoReq();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateOrUpdateItemInfoReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            itemId_ = input.readUInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            itemName_ = s;
            break;
          }
          case 24: {

            categoryId_ = input.readUInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            categoryNam_ = s;
            break;
          }
          case 40: {

            shopId_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.wechatmerchant.skurpc.Sku.internal_static_sku_CreateOrUpdateItemInfoReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.wechatmerchant.skurpc.Sku.internal_static_sku_CreateOrUpdateItemInfoReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq.class, com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq.Builder.class);
  }

  public static final int ITEM_ID_FIELD_NUMBER = 1;
  private int itemId_;
  /**
   * <code>uint32 item_id = 1;</code>
   * @return The itemId.
   */
  @java.lang.Override
  public int getItemId() {
    return itemId_;
  }

  public static final int ITEM_NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object itemName_;
  /**
   * <code>string item_name = 2;</code>
   * @return The itemName.
   */
  @java.lang.Override
  public java.lang.String getItemName() {
    java.lang.Object ref = itemName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      itemName_ = s;
      return s;
    }
  }
  /**
   * <code>string item_name = 2;</code>
   * @return The bytes for itemName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getItemNameBytes() {
    java.lang.Object ref = itemName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      itemName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CATEGORY_ID_FIELD_NUMBER = 3;
  private int categoryId_;
  /**
   * <code>uint32 category_id = 3;</code>
   * @return The categoryId.
   */
  @java.lang.Override
  public int getCategoryId() {
    return categoryId_;
  }

  public static final int CATEGORY_NAM_FIELD_NUMBER = 4;
  private volatile java.lang.Object categoryNam_;
  /**
   * <code>string category_nam = 4;</code>
   * @return The categoryNam.
   */
  @java.lang.Override
  public java.lang.String getCategoryNam() {
    java.lang.Object ref = categoryNam_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      categoryNam_ = s;
      return s;
    }
  }
  /**
   * <code>string category_nam = 4;</code>
   * @return The bytes for categoryNam.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCategoryNamBytes() {
    java.lang.Object ref = categoryNam_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      categoryNam_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SHOP_ID_FIELD_NUMBER = 5;
  private int shopId_;
  /**
   * <code>uint32 shop_id = 5;</code>
   * @return The shopId.
   */
  @java.lang.Override
  public int getShopId() {
    return shopId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (itemId_ != 0) {
      output.writeUInt32(1, itemId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(itemName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, itemName_);
    }
    if (categoryId_ != 0) {
      output.writeUInt32(3, categoryId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(categoryNam_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, categoryNam_);
    }
    if (shopId_ != 0) {
      output.writeUInt32(5, shopId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (itemId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, itemId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(itemName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, itemName_);
    }
    if (categoryId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, categoryId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(categoryNam_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, categoryNam_);
    }
    if (shopId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, shopId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq)) {
      return super.equals(obj);
    }
    com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq other = (com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq) obj;

    if (getItemId()
        != other.getItemId()) return false;
    if (!getItemName()
        .equals(other.getItemName())) return false;
    if (getCategoryId()
        != other.getCategoryId()) return false;
    if (!getCategoryNam()
        .equals(other.getCategoryNam())) return false;
    if (getShopId()
        != other.getShopId()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ITEM_ID_FIELD_NUMBER;
    hash = (53 * hash) + getItemId();
    hash = (37 * hash) + ITEM_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getItemName().hashCode();
    hash = (37 * hash) + CATEGORY_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCategoryId();
    hash = (37 * hash) + CATEGORY_NAM_FIELD_NUMBER;
    hash = (53 * hash) + getCategoryNam().hashCode();
    hash = (37 * hash) + SHOP_ID_FIELD_NUMBER;
    hash = (53 * hash) + getShopId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code sku.CreateOrUpdateItemInfoReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sku.CreateOrUpdateItemInfoReq)
      com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.wechatmerchant.skurpc.Sku.internal_static_sku_CreateOrUpdateItemInfoReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.wechatmerchant.skurpc.Sku.internal_static_sku_CreateOrUpdateItemInfoReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq.class, com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq.Builder.class);
    }

    // Construct using com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      itemId_ = 0;

      itemName_ = "";

      categoryId_ = 0;

      categoryNam_ = "";

      shopId_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.wechatmerchant.skurpc.Sku.internal_static_sku_CreateOrUpdateItemInfoReq_descriptor;
    }

    @java.lang.Override
    public com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq getDefaultInstanceForType() {
      return com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq build() {
      com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq buildPartial() {
      com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq result = new com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq(this);
      result.itemId_ = itemId_;
      result.itemName_ = itemName_;
      result.categoryId_ = categoryId_;
      result.categoryNam_ = categoryNam_;
      result.shopId_ = shopId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq) {
        return mergeFrom((com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq other) {
      if (other == com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq.getDefaultInstance()) return this;
      if (other.getItemId() != 0) {
        setItemId(other.getItemId());
      }
      if (!other.getItemName().isEmpty()) {
        itemName_ = other.itemName_;
        onChanged();
      }
      if (other.getCategoryId() != 0) {
        setCategoryId(other.getCategoryId());
      }
      if (!other.getCategoryNam().isEmpty()) {
        categoryNam_ = other.categoryNam_;
        onChanged();
      }
      if (other.getShopId() != 0) {
        setShopId(other.getShopId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int itemId_ ;
    /**
     * <code>uint32 item_id = 1;</code>
     * @return The itemId.
     */
    @java.lang.Override
    public int getItemId() {
      return itemId_;
    }
    /**
     * <code>uint32 item_id = 1;</code>
     * @param value The itemId to set.
     * @return This builder for chaining.
     */
    public Builder setItemId(int value) {
      
      itemId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 item_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearItemId() {
      
      itemId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object itemName_ = "";
    /**
     * <code>string item_name = 2;</code>
     * @return The itemName.
     */
    public java.lang.String getItemName() {
      java.lang.Object ref = itemName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        itemName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string item_name = 2;</code>
     * @return The bytes for itemName.
     */
    public com.google.protobuf.ByteString
        getItemNameBytes() {
      java.lang.Object ref = itemName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        itemName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string item_name = 2;</code>
     * @param value The itemName to set.
     * @return This builder for chaining.
     */
    public Builder setItemName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      itemName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string item_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearItemName() {
      
      itemName_ = getDefaultInstance().getItemName();
      onChanged();
      return this;
    }
    /**
     * <code>string item_name = 2;</code>
     * @param value The bytes for itemName to set.
     * @return This builder for chaining.
     */
    public Builder setItemNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      itemName_ = value;
      onChanged();
      return this;
    }

    private int categoryId_ ;
    /**
     * <code>uint32 category_id = 3;</code>
     * @return The categoryId.
     */
    @java.lang.Override
    public int getCategoryId() {
      return categoryId_;
    }
    /**
     * <code>uint32 category_id = 3;</code>
     * @param value The categoryId to set.
     * @return This builder for chaining.
     */
    public Builder setCategoryId(int value) {
      
      categoryId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 category_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCategoryId() {
      
      categoryId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object categoryNam_ = "";
    /**
     * <code>string category_nam = 4;</code>
     * @return The categoryNam.
     */
    public java.lang.String getCategoryNam() {
      java.lang.Object ref = categoryNam_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        categoryNam_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string category_nam = 4;</code>
     * @return The bytes for categoryNam.
     */
    public com.google.protobuf.ByteString
        getCategoryNamBytes() {
      java.lang.Object ref = categoryNam_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        categoryNam_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string category_nam = 4;</code>
     * @param value The categoryNam to set.
     * @return This builder for chaining.
     */
    public Builder setCategoryNam(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      categoryNam_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string category_nam = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCategoryNam() {
      
      categoryNam_ = getDefaultInstance().getCategoryNam();
      onChanged();
      return this;
    }
    /**
     * <code>string category_nam = 4;</code>
     * @param value The bytes for categoryNam to set.
     * @return This builder for chaining.
     */
    public Builder setCategoryNamBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      categoryNam_ = value;
      onChanged();
      return this;
    }

    private int shopId_ ;
    /**
     * <code>uint32 shop_id = 5;</code>
     * @return The shopId.
     */
    @java.lang.Override
    public int getShopId() {
      return shopId_;
    }
    /**
     * <code>uint32 shop_id = 5;</code>
     * @param value The shopId to set.
     * @return This builder for chaining.
     */
    public Builder setShopId(int value) {
      
      shopId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 shop_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearShopId() {
      
      shopId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:sku.CreateOrUpdateItemInfoReq)
  }

  // @@protoc_insertion_point(class_scope:sku.CreateOrUpdateItemInfoReq)
  private static final com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq();
  }

  public static com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateOrUpdateItemInfoReq>
      PARSER = new com.google.protobuf.AbstractParser<CreateOrUpdateItemInfoReq>() {
    @java.lang.Override
    public CreateOrUpdateItemInfoReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateOrUpdateItemInfoReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateOrUpdateItemInfoReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateOrUpdateItemInfoReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.wechatmerchant.skurpc.CreateOrUpdateItemInfoReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

