// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/sku.proto

// Protobuf Java Version: 3.25.3
package com.example.wechatmerchant.skurpc;

public interface CreateSkuReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sku.CreateSkuReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string item_id = 1;</code>
   * @return The itemId.
   */
  java.lang.String getItemId();
  /**
   * <code>string item_id = 1;</code>
   * @return The bytes for itemId.
   */
  com.google.protobuf.ByteString
      getItemIdBytes();

  /**
   * <code>string item_nam = 2;</code>
   * @return The itemNam.
   */
  java.lang.String getItemNam();
  /**
   * <code>string item_nam = 2;</code>
   * @return The bytes for itemNam.
   */
  com.google.protobuf.ByteString
      getItemNamBytes();

  /**
   * <code>string product_id = 3;</code>
   * @return The productId.
   */
  java.lang.String getProductId();
  /**
   * <code>string product_id = 3;</code>
   * @return The bytes for productId.
   */
  com.google.protobuf.ByteString
      getProductIdBytes();

  /**
   * <code>string product_name = 4;</code>
   * @return The productName.
   */
  java.lang.String getProductName();
  /**
   * <code>string product_name = 4;</code>
   * @return The bytes for productName.
   */
  com.google.protobuf.ByteString
      getProductNameBytes();

  /**
   * <code>uint32 inventory_qty = 5;</code>
   * @return The inventoryQty.
   */
  int getInventoryQty();
}
