// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/sku.proto

// Protobuf Java Version: 3.25.3
package com.example.wechatmerchant.skurpc;

public interface GetShopInfoReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sku.GetShopInfoReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 shop_id = 1;</code>
   * @return The shopId.
   */
  int getShopId();

  /**
   * <code>string shop_name = 2;</code>
   * @return The shopName.
   */
  java.lang.String getShopName();
  /**
   * <code>string shop_name = 2;</code>
   * @return The bytes for shopName.
   */
  com.google.protobuf.ByteString
      getShopNameBytes();
}
