// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/sku.proto

// Protobuf Java Version: 3.25.3
package com.example.wechatmerchant.skurpc;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sku.Response)
    com.google.protobuf.MessageOrBuilder {
}
