// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/sku.proto

package com.example.wechatmerchant.skurpc;

public final class Sku {
  private Sku() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sku_CommonRsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sku_CommonRsp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sku_SkuReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sku_SkuReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sku_SkuResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sku_SkuResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sku_SkuInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sku_SkuInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sku_CreateOrUpdateSkuReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sku_CreateOrUpdateSkuReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sku_SkuInventoryReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sku_SkuInventoryReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sku_SkuInventoryResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sku_SkuInventoryResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sku_SkuInventoryInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sku_SkuInventoryInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\030src/main/proto/sku.proto\022\003sku\"&\n\tCommo" +
      "nRsp\022\014\n\004code\030\001 \001(\004\022\013\n\003msg\030\002 \001(\t\"@\n\006SkuRe" +
      "q\022\016\n\006sku_id\030\001 \003(\t\022\023\n\013page_number\030\002 \001(\004\022\021" +
      "\n\tpage_size\030\003 \001(\004\"T\n\007SkuResp\022\036\n\006common\030\001" +
      " \001(\0132\016.sku.CommonRsp\022\032\n\004data\030\002 \003(\0132\014.sku" +
      ".SkuInfo\022\r\n\005total\030\003 \001(\004\"\252\001\n\007SkuInfo\022\016\n\006s" +
      "ku_id\030\001 \001(\t\022\020\n\010sku_name\030\002 \001(\t\022\021\n\tsku_ima" +
      "ge\030\003 \001(\t\022\017\n\007item_id\030\004 \001(\r\022\021\n\titem_name\030\005" +
      " \001(\t\022\022\n\nproduct_id\030\006 \001(\r\022\024\n\014product_name" +
      "\030\007 \001(\t\022\r\n\005ctime\030\010 \001(\004\022\r\n\005mtime\030\t \001(\004\"^\n\024" +
      "CreateOrUpdateSkuReq\022\016\n\006sku_id\030\001 \001(\t\022\020\n\010" +
      "sku_name\030\002 \001(\t\022\021\n\tsku_image\030\003 \001(\t\022\021\n\tsku" +
      "_count\030\004 \001(\t\"!\n\017SkuInventoryReq\022\016\n\006sku_i" +
      "d\030\001 \001(\t\"W\n\020SkuInventoryResp\022\036\n\006common\030\001 " +
      "\001(\0132\016.sku.CommonRsp\022#\n\004data\030\002 \003(\0132\025.sku." +
      "SkuInventoryInfo\"M\n\020SkuInventoryInfo\022\016\n\006" +
      "sku_id\030\001 \001(\t\022\025\n\rinventory_qty\030\002 \001(\004\022\022\n\nd" +
      "amage_qty\030\003 \001(\0042\352\001\n\nSkuService\022\'\n\nGetSku" +
      "Info\022\013.sku.SkuReq\032\014.sku.SkuResp\022:\n\rCreat" +
      "eSkuInfo\022\031.sku.CreateOrUpdateSkuReq\032\016.sk" +
      "u.CommonRsp\0223\n\006Update\022\031.sku.CreateOrUpda" +
      "teSkuReq\032\016.sku.CommonRsp\022B\n\023GetSkuInvent" +
      "oryInfo\022\024.sku.SkuInventoryReq\032\025.sku.SkuI" +
      "nventoryRespB,\n!com.example.wechatmercha" +
      "nt.skurpcP\001Z\005./skub\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_sku_CommonRsp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sku_CommonRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sku_CommonRsp_descriptor,
        new String[] { "Code", "Msg", });
    internal_static_sku_SkuReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sku_SkuReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sku_SkuReq_descriptor,
        new String[] { "SkuId", "PageNumber", "PageSize", });
    internal_static_sku_SkuResp_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_sku_SkuResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sku_SkuResp_descriptor,
        new String[] { "Common", "Data", "Total", });
    internal_static_sku_SkuInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_sku_SkuInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sku_SkuInfo_descriptor,
        new String[] { "SkuId", "SkuName", "SkuImage", "ItemId", "ItemName", "ProductId", "ProductName", "Ctime", "Mtime", });
    internal_static_sku_CreateOrUpdateSkuReq_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_sku_CreateOrUpdateSkuReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sku_CreateOrUpdateSkuReq_descriptor,
        new String[] { "SkuId", "SkuName", "SkuImage", "SkuCount", });
    internal_static_sku_SkuInventoryReq_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_sku_SkuInventoryReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sku_SkuInventoryReq_descriptor,
        new String[] { "SkuId", });
    internal_static_sku_SkuInventoryResp_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_sku_SkuInventoryResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sku_SkuInventoryResp_descriptor,
        new String[] { "Common", "Data", });
    internal_static_sku_SkuInventoryInfo_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_sku_SkuInventoryInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sku_SkuInventoryInfo_descriptor,
        new String[] { "SkuId", "InventoryQty", "DamageQty", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
