// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb/sku.proto

package com.example.wechatmerchant.skurpc;

public final class Sku {
  private Sku() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sku_CommonRsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sku_CommonRsp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sku_SkuReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sku_SkuReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sku_SkuResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sku_SkuResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sku_SkuInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sku_SkuInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sku_CreateOrUpdateSkuReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sku_CreateOrUpdateSkuReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014pb/sku.proto\022\003sku\"&\n\tCommonRsp\022\014\n\004code" +
      "\030\001 \001(\004\022\013\n\003msg\030\002 \001(\t\"n\n\006SkuReq\022\016\n\006sku_id\030" +
      "\001 \001(\t\022\020\n\010sku_name\030\002 \001(\t\022\021\n\tsku_image\030\003 \001" +
      "(\t\022\021\n\tsku_count\030\004 \001(\t\022\r\n\005ctime\030\005 \001(\004\022\r\n\005" +
      "mtime\030\006 \001(\004\"E\n\007SkuResp\022\036\n\006common\030\001 \001(\0132\016" +
      ".sku.CommonRsp\022\032\n\004data\030\002 \003(\0132\014.sku.SkuIn" +
      "fo\"o\n\007SkuInfo\022\016\n\006sku_id\030\001 \001(\t\022\020\n\010sku_nam" +
      "e\030\002 \001(\t\022\021\n\tsku_image\030\003 \001(\t\022\021\n\tsku_count\030" +
      "\004 \001(\t\022\r\n\005ctime\030\005 \001(\004\022\r\n\005mtime\030\006 \001(\004\"^\n\024C" +
      "reateOrUpdateSkuReq\022\016\n\006sku_id\030\001 \001(\t\022\020\n\010s" +
      "ku_name\030\002 \001(\t\022\021\n\tsku_image\030\003 \001(\t\022\021\n\tsku_" +
      "count\030\004 \001(\t2\246\001\n\nSkuService\022\'\n\nGetSkuInfo" +
      "\022\013.sku.SkuReq\032\014.sku.SkuResp\022:\n\rCreateSku" +
      "Info\022\031.sku.CreateOrUpdateSkuReq\032\016.sku.Co" +
      "mmonRsp\0223\n\006Update\022\031.sku.CreateOrUpdateSk" +
      "uReq\032\016.sku.CommonRspB,\n!com.example.wech" +
      "atmerchant.skurpcP\001Z\005./skub\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_sku_CommonRsp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sku_CommonRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sku_CommonRsp_descriptor,
        new java.lang.String[] { "Code", "Msg", });
    internal_static_sku_SkuReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sku_SkuReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sku_SkuReq_descriptor,
        new java.lang.String[] { "SkuId", "SkuName", "SkuImage", "SkuCount", "Ctime", "Mtime", });
    internal_static_sku_SkuResp_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_sku_SkuResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sku_SkuResp_descriptor,
        new java.lang.String[] { "Common", "Data", });
    internal_static_sku_SkuInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_sku_SkuInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sku_SkuInfo_descriptor,
        new java.lang.String[] { "SkuId", "SkuName", "SkuImage", "SkuCount", "Ctime", "Mtime", });
    internal_static_sku_CreateOrUpdateSkuReq_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_sku_CreateOrUpdateSkuReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sku_CreateOrUpdateSkuReq_descriptor,
        new java.lang.String[] { "SkuId", "SkuName", "SkuImage", "SkuCount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
