// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/sku.proto

// Protobuf Java Version: 3.25.3
package com.example.wechatmerchant.skurpc;

/**
 * Protobuf type {@code sku.SkuInfo}
 */
public final class SkuInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:sku.SkuInfo)
    SkuInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SkuInfo.newBuilder() to construct.
  private SkuInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SkuInfo() {
    skuId_ = "";
    skuName_ = "";
    skuImage_ = "";
    itemName_ = "";
    productName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SkuInfo();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.wechatmerchant.skurpc.Sku.internal_static_sku_SkuInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.wechatmerchant.skurpc.Sku.internal_static_sku_SkuInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.wechatmerchant.skurpc.SkuInfo.class, com.example.wechatmerchant.skurpc.SkuInfo.Builder.class);
  }

  public static final int SKU_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object skuId_ = "";
  /**
   * <code>string sku_id = 1;</code>
   * @return The skuId.
   */
  @java.lang.Override
  public java.lang.String getSkuId() {
    java.lang.Object ref = skuId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      skuId_ = s;
      return s;
    }
  }
  /**
   * <code>string sku_id = 1;</code>
   * @return The bytes for skuId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSkuIdBytes() {
    java.lang.Object ref = skuId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      skuId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SKU_NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object skuName_ = "";
  /**
   * <code>string sku_name = 2;</code>
   * @return The skuName.
   */
  @java.lang.Override
  public java.lang.String getSkuName() {
    java.lang.Object ref = skuName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      skuName_ = s;
      return s;
    }
  }
  /**
   * <code>string sku_name = 2;</code>
   * @return The bytes for skuName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSkuNameBytes() {
    java.lang.Object ref = skuName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      skuName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SKU_IMAGE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object skuImage_ = "";
  /**
   * <code>string sku_image = 3;</code>
   * @return The skuImage.
   */
  @java.lang.Override
  public java.lang.String getSkuImage() {
    java.lang.Object ref = skuImage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      skuImage_ = s;
      return s;
    }
  }
  /**
   * <code>string sku_image = 3;</code>
   * @return The bytes for skuImage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSkuImageBytes() {
    java.lang.Object ref = skuImage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      skuImage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ITEM_ID_FIELD_NUMBER = 4;
  private int itemId_ = 0;
  /**
   * <code>uint32 item_id = 4;</code>
   * @return The itemId.
   */
  @java.lang.Override
  public int getItemId() {
    return itemId_;
  }

  public static final int ITEM_NAME_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object itemName_ = "";
  /**
   * <code>string item_name = 5;</code>
   * @return The itemName.
   */
  @java.lang.Override
  public java.lang.String getItemName() {
    java.lang.Object ref = itemName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      itemName_ = s;
      return s;
    }
  }
  /**
   * <code>string item_name = 5;</code>
   * @return The bytes for itemName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getItemNameBytes() {
    java.lang.Object ref = itemName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      itemName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRODUCT_ID_FIELD_NUMBER = 6;
  private int productId_ = 0;
  /**
   * <code>uint32 product_id = 6;</code>
   * @return The productId.
   */
  @java.lang.Override
  public int getProductId() {
    return productId_;
  }

  public static final int PRODUCT_NAME_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object productName_ = "";
  /**
   * <code>string product_name = 7;</code>
   * @return The productName.
   */
  @java.lang.Override
  public java.lang.String getProductName() {
    java.lang.Object ref = productName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productName_ = s;
      return s;
    }
  }
  /**
   * <code>string product_name = 7;</code>
   * @return The bytes for productName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProductNameBytes() {
    java.lang.Object ref = productName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CTIME_FIELD_NUMBER = 8;
  private int ctime_ = 0;
  /**
   * <code>uint32 ctime = 8;</code>
   * @return The ctime.
   */
  @java.lang.Override
  public int getCtime() {
    return ctime_;
  }

  public static final int MTIME_FIELD_NUMBER = 9;
  private int mtime_ = 0;
  /**
   * <code>uint32 mtime = 9;</code>
   * @return The mtime.
   */
  @java.lang.Override
  public int getMtime() {
    return mtime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(skuId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, skuId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(skuName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, skuName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(skuImage_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, skuImage_);
    }
    if (itemId_ != 0) {
      output.writeUInt32(4, itemId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(itemName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, itemName_);
    }
    if (productId_ != 0) {
      output.writeUInt32(6, productId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, productName_);
    }
    if (ctime_ != 0) {
      output.writeUInt32(8, ctime_);
    }
    if (mtime_ != 0) {
      output.writeUInt32(9, mtime_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(skuId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, skuId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(skuName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, skuName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(skuImage_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, skuImage_);
    }
    if (itemId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, itemId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(itemName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, itemName_);
    }
    if (productId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, productId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, productName_);
    }
    if (ctime_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(8, ctime_);
    }
    if (mtime_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(9, mtime_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.wechatmerchant.skurpc.SkuInfo)) {
      return super.equals(obj);
    }
    com.example.wechatmerchant.skurpc.SkuInfo other = (com.example.wechatmerchant.skurpc.SkuInfo) obj;

    if (!getSkuId()
        .equals(other.getSkuId())) return false;
    if (!getSkuName()
        .equals(other.getSkuName())) return false;
    if (!getSkuImage()
        .equals(other.getSkuImage())) return false;
    if (getItemId()
        != other.getItemId()) return false;
    if (!getItemName()
        .equals(other.getItemName())) return false;
    if (getProductId()
        != other.getProductId()) return false;
    if (!getProductName()
        .equals(other.getProductName())) return false;
    if (getCtime()
        != other.getCtime()) return false;
    if (getMtime()
        != other.getMtime()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SKU_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSkuId().hashCode();
    hash = (37 * hash) + SKU_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getSkuName().hashCode();
    hash = (37 * hash) + SKU_IMAGE_FIELD_NUMBER;
    hash = (53 * hash) + getSkuImage().hashCode();
    hash = (37 * hash) + ITEM_ID_FIELD_NUMBER;
    hash = (53 * hash) + getItemId();
    hash = (37 * hash) + ITEM_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getItemName().hashCode();
    hash = (37 * hash) + PRODUCT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getProductId();
    hash = (37 * hash) + PRODUCT_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getProductName().hashCode();
    hash = (37 * hash) + CTIME_FIELD_NUMBER;
    hash = (53 * hash) + getCtime();
    hash = (37 * hash) + MTIME_FIELD_NUMBER;
    hash = (53 * hash) + getMtime();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.wechatmerchant.skurpc.SkuInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.wechatmerchant.skurpc.SkuInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.wechatmerchant.skurpc.SkuInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.wechatmerchant.skurpc.SkuInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.wechatmerchant.skurpc.SkuInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.wechatmerchant.skurpc.SkuInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.wechatmerchant.skurpc.SkuInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.wechatmerchant.skurpc.SkuInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.wechatmerchant.skurpc.SkuInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.wechatmerchant.skurpc.SkuInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.wechatmerchant.skurpc.SkuInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.wechatmerchant.skurpc.SkuInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.wechatmerchant.skurpc.SkuInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code sku.SkuInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sku.SkuInfo)
      com.example.wechatmerchant.skurpc.SkuInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.wechatmerchant.skurpc.Sku.internal_static_sku_SkuInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.wechatmerchant.skurpc.Sku.internal_static_sku_SkuInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.wechatmerchant.skurpc.SkuInfo.class, com.example.wechatmerchant.skurpc.SkuInfo.Builder.class);
    }

    // Construct using com.example.wechatmerchant.skurpc.SkuInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      skuId_ = "";
      skuName_ = "";
      skuImage_ = "";
      itemId_ = 0;
      itemName_ = "";
      productId_ = 0;
      productName_ = "";
      ctime_ = 0;
      mtime_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.wechatmerchant.skurpc.Sku.internal_static_sku_SkuInfo_descriptor;
    }

    @java.lang.Override
    public com.example.wechatmerchant.skurpc.SkuInfo getDefaultInstanceForType() {
      return com.example.wechatmerchant.skurpc.SkuInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.wechatmerchant.skurpc.SkuInfo build() {
      com.example.wechatmerchant.skurpc.SkuInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.wechatmerchant.skurpc.SkuInfo buildPartial() {
      com.example.wechatmerchant.skurpc.SkuInfo result = new com.example.wechatmerchant.skurpc.SkuInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.wechatmerchant.skurpc.SkuInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.skuId_ = skuId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.skuName_ = skuName_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.skuImage_ = skuImage_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.itemId_ = itemId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.itemName_ = itemName_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.productId_ = productId_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.productName_ = productName_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.ctime_ = ctime_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.mtime_ = mtime_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.wechatmerchant.skurpc.SkuInfo) {
        return mergeFrom((com.example.wechatmerchant.skurpc.SkuInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.wechatmerchant.skurpc.SkuInfo other) {
      if (other == com.example.wechatmerchant.skurpc.SkuInfo.getDefaultInstance()) return this;
      if (!other.getSkuId().isEmpty()) {
        skuId_ = other.skuId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getSkuName().isEmpty()) {
        skuName_ = other.skuName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getSkuImage().isEmpty()) {
        skuImage_ = other.skuImage_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getItemId() != 0) {
        setItemId(other.getItemId());
      }
      if (!other.getItemName().isEmpty()) {
        itemName_ = other.itemName_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getProductId() != 0) {
        setProductId(other.getProductId());
      }
      if (!other.getProductName().isEmpty()) {
        productName_ = other.productName_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (other.getCtime() != 0) {
        setCtime(other.getCtime());
      }
      if (other.getMtime() != 0) {
        setMtime(other.getMtime());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              skuId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              skuName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              skuImage_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              itemId_ = input.readUInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              itemName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              productId_ = input.readUInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              productName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 64: {
              ctime_ = input.readUInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              mtime_ = input.readUInt32();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object skuId_ = "";
    /**
     * <code>string sku_id = 1;</code>
     * @return The skuId.
     */
    public java.lang.String getSkuId() {
      java.lang.Object ref = skuId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        skuId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sku_id = 1;</code>
     * @return The bytes for skuId.
     */
    public com.google.protobuf.ByteString
        getSkuIdBytes() {
      java.lang.Object ref = skuId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        skuId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sku_id = 1;</code>
     * @param value The skuId to set.
     * @return This builder for chaining.
     */
    public Builder setSkuId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      skuId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string sku_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSkuId() {
      skuId_ = getDefaultInstance().getSkuId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string sku_id = 1;</code>
     * @param value The bytes for skuId to set.
     * @return This builder for chaining.
     */
    public Builder setSkuIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      skuId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object skuName_ = "";
    /**
     * <code>string sku_name = 2;</code>
     * @return The skuName.
     */
    public java.lang.String getSkuName() {
      java.lang.Object ref = skuName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        skuName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sku_name = 2;</code>
     * @return The bytes for skuName.
     */
    public com.google.protobuf.ByteString
        getSkuNameBytes() {
      java.lang.Object ref = skuName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        skuName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sku_name = 2;</code>
     * @param value The skuName to set.
     * @return This builder for chaining.
     */
    public Builder setSkuName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      skuName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string sku_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSkuName() {
      skuName_ = getDefaultInstance().getSkuName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string sku_name = 2;</code>
     * @param value The bytes for skuName to set.
     * @return This builder for chaining.
     */
    public Builder setSkuNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      skuName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object skuImage_ = "";
    /**
     * <code>string sku_image = 3;</code>
     * @return The skuImage.
     */
    public java.lang.String getSkuImage() {
      java.lang.Object ref = skuImage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        skuImage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sku_image = 3;</code>
     * @return The bytes for skuImage.
     */
    public com.google.protobuf.ByteString
        getSkuImageBytes() {
      java.lang.Object ref = skuImage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        skuImage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sku_image = 3;</code>
     * @param value The skuImage to set.
     * @return This builder for chaining.
     */
    public Builder setSkuImage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      skuImage_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string sku_image = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSkuImage() {
      skuImage_ = getDefaultInstance().getSkuImage();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string sku_image = 3;</code>
     * @param value The bytes for skuImage to set.
     * @return This builder for chaining.
     */
    public Builder setSkuImageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      skuImage_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int itemId_ ;
    /**
     * <code>uint32 item_id = 4;</code>
     * @return The itemId.
     */
    @java.lang.Override
    public int getItemId() {
      return itemId_;
    }
    /**
     * <code>uint32 item_id = 4;</code>
     * @param value The itemId to set.
     * @return This builder for chaining.
     */
    public Builder setItemId(int value) {

      itemId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 item_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearItemId() {
      bitField0_ = (bitField0_ & ~0x00000008);
      itemId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object itemName_ = "";
    /**
     * <code>string item_name = 5;</code>
     * @return The itemName.
     */
    public java.lang.String getItemName() {
      java.lang.Object ref = itemName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        itemName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string item_name = 5;</code>
     * @return The bytes for itemName.
     */
    public com.google.protobuf.ByteString
        getItemNameBytes() {
      java.lang.Object ref = itemName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        itemName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string item_name = 5;</code>
     * @param value The itemName to set.
     * @return This builder for chaining.
     */
    public Builder setItemName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      itemName_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string item_name = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearItemName() {
      itemName_ = getDefaultInstance().getItemName();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string item_name = 5;</code>
     * @param value The bytes for itemName to set.
     * @return This builder for chaining.
     */
    public Builder setItemNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      itemName_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private int productId_ ;
    /**
     * <code>uint32 product_id = 6;</code>
     * @return The productId.
     */
    @java.lang.Override
    public int getProductId() {
      return productId_;
    }
    /**
     * <code>uint32 product_id = 6;</code>
     * @param value The productId to set.
     * @return This builder for chaining.
     */
    public Builder setProductId(int value) {

      productId_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 product_id = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductId() {
      bitField0_ = (bitField0_ & ~0x00000020);
      productId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object productName_ = "";
    /**
     * <code>string product_name = 7;</code>
     * @return The productName.
     */
    public java.lang.String getProductName() {
      java.lang.Object ref = productName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string product_name = 7;</code>
     * @return The bytes for productName.
     */
    public com.google.protobuf.ByteString
        getProductNameBytes() {
      java.lang.Object ref = productName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string product_name = 7;</code>
     * @param value The productName to set.
     * @return This builder for chaining.
     */
    public Builder setProductName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      productName_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string product_name = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductName() {
      productName_ = getDefaultInstance().getProductName();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string product_name = 7;</code>
     * @param value The bytes for productName to set.
     * @return This builder for chaining.
     */
    public Builder setProductNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      productName_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private int ctime_ ;
    /**
     * <code>uint32 ctime = 8;</code>
     * @return The ctime.
     */
    @java.lang.Override
    public int getCtime() {
      return ctime_;
    }
    /**
     * <code>uint32 ctime = 8;</code>
     * @param value The ctime to set.
     * @return This builder for chaining.
     */
    public Builder setCtime(int value) {

      ctime_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 ctime = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearCtime() {
      bitField0_ = (bitField0_ & ~0x00000080);
      ctime_ = 0;
      onChanged();
      return this;
    }

    private int mtime_ ;
    /**
     * <code>uint32 mtime = 9;</code>
     * @return The mtime.
     */
    @java.lang.Override
    public int getMtime() {
      return mtime_;
    }
    /**
     * <code>uint32 mtime = 9;</code>
     * @param value The mtime to set.
     * @return This builder for chaining.
     */
    public Builder setMtime(int value) {

      mtime_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 mtime = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearMtime() {
      bitField0_ = (bitField0_ & ~0x00000100);
      mtime_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:sku.SkuInfo)
  }

  // @@protoc_insertion_point(class_scope:sku.SkuInfo)
  private static final com.example.wechatmerchant.skurpc.SkuInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.wechatmerchant.skurpc.SkuInfo();
  }

  public static com.example.wechatmerchant.skurpc.SkuInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SkuInfo>
      PARSER = new com.google.protobuf.AbstractParser<SkuInfo>() {
    @java.lang.Override
    public SkuInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SkuInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SkuInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.wechatmerchant.skurpc.SkuInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

