// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/sku.proto

package com.example.wechatmerchant.skurpc;

/**
 * Protobuf type {@code sku.SkuInventoryInfo}
 */
public final class SkuInventoryInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:sku.SkuInventoryInfo)
    SkuInventoryInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SkuInventoryInfo.newBuilder() to construct.
  private SkuInventoryInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SkuInventoryInfo() {
    skuId_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new SkuInventoryInfo();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SkuInventoryInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            skuId_ = s;
            break;
          }
          case 16: {

            inventoryQty_ = input.readUInt64();
            break;
          }
          case 24: {

            damageQty_ = input.readUInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Sku.internal_static_sku_SkuInventoryInfo_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Sku.internal_static_sku_SkuInventoryInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            SkuInventoryInfo.class, Builder.class);
  }

  public static final int SKU_ID_FIELD_NUMBER = 1;
  private volatile Object skuId_;
  /**
   * <code>string sku_id = 1;</code>
   * @return The skuId.
   */
  @Override
  public String getSkuId() {
    Object ref = skuId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      skuId_ = s;
      return s;
    }
  }
  /**
   * <code>string sku_id = 1;</code>
   * @return The bytes for skuId.
   */
  @Override
  public com.google.protobuf.ByteString
      getSkuIdBytes() {
    Object ref = skuId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      skuId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INVENTORY_QTY_FIELD_NUMBER = 2;
  private long inventoryQty_;
  /**
   * <code>uint64 inventory_qty = 2;</code>
   * @return The inventoryQty.
   */
  @Override
  public long getInventoryQty() {
    return inventoryQty_;
  }

  public static final int DAMAGE_QTY_FIELD_NUMBER = 3;
  private long damageQty_;
  /**
   * <code>uint64 damage_qty = 3;</code>
   * @return The damageQty.
   */
  @Override
  public long getDamageQty() {
    return damageQty_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(skuId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, skuId_);
    }
    if (inventoryQty_ != 0L) {
      output.writeUInt64(2, inventoryQty_);
    }
    if (damageQty_ != 0L) {
      output.writeUInt64(3, damageQty_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(skuId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, skuId_);
    }
    if (inventoryQty_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, inventoryQty_);
    }
    if (damageQty_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, damageQty_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof SkuInventoryInfo)) {
      return super.equals(obj);
    }
    SkuInventoryInfo other = (SkuInventoryInfo) obj;

    if (!getSkuId()
        .equals(other.getSkuId())) return false;
    if (getInventoryQty()
        != other.getInventoryQty()) return false;
    if (getDamageQty()
        != other.getDamageQty()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SKU_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSkuId().hashCode();
    hash = (37 * hash) + INVENTORY_QTY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getInventoryQty());
    hash = (37 * hash) + DAMAGE_QTY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDamageQty());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static SkuInventoryInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SkuInventoryInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SkuInventoryInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SkuInventoryInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SkuInventoryInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SkuInventoryInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SkuInventoryInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SkuInventoryInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static SkuInventoryInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static SkuInventoryInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static SkuInventoryInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SkuInventoryInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(SkuInventoryInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code sku.SkuInventoryInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sku.SkuInventoryInfo)
      SkuInventoryInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Sku.internal_static_sku_SkuInventoryInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Sku.internal_static_sku_SkuInventoryInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SkuInventoryInfo.class, Builder.class);
    }

    // Construct using com.example.wechatmerchant.skurpc.SkuInventoryInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      skuId_ = "";

      inventoryQty_ = 0L;

      damageQty_ = 0L;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Sku.internal_static_sku_SkuInventoryInfo_descriptor;
    }

    @Override
    public SkuInventoryInfo getDefaultInstanceForType() {
      return SkuInventoryInfo.getDefaultInstance();
    }

    @Override
    public SkuInventoryInfo build() {
      SkuInventoryInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public SkuInventoryInfo buildPartial() {
      SkuInventoryInfo result = new SkuInventoryInfo(this);
      result.skuId_ = skuId_;
      result.inventoryQty_ = inventoryQty_;
      result.damageQty_ = damageQty_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof SkuInventoryInfo) {
        return mergeFrom((SkuInventoryInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(SkuInventoryInfo other) {
      if (other == SkuInventoryInfo.getDefaultInstance()) return this;
      if (!other.getSkuId().isEmpty()) {
        skuId_ = other.skuId_;
        onChanged();
      }
      if (other.getInventoryQty() != 0L) {
        setInventoryQty(other.getInventoryQty());
      }
      if (other.getDamageQty() != 0L) {
        setDamageQty(other.getDamageQty());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      SkuInventoryInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (SkuInventoryInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object skuId_ = "";
    /**
     * <code>string sku_id = 1;</code>
     * @return The skuId.
     */
    public String getSkuId() {
      Object ref = skuId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        skuId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string sku_id = 1;</code>
     * @return The bytes for skuId.
     */
    public com.google.protobuf.ByteString
        getSkuIdBytes() {
      Object ref = skuId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        skuId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sku_id = 1;</code>
     * @param value The skuId to set.
     * @return This builder for chaining.
     */
    public Builder setSkuId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      skuId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sku_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSkuId() {
      
      skuId_ = getDefaultInstance().getSkuId();
      onChanged();
      return this;
    }
    /**
     * <code>string sku_id = 1;</code>
     * @param value The bytes for skuId to set.
     * @return This builder for chaining.
     */
    public Builder setSkuIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      skuId_ = value;
      onChanged();
      return this;
    }

    private long inventoryQty_ ;
    /**
     * <code>uint64 inventory_qty = 2;</code>
     * @return The inventoryQty.
     */
    @Override
    public long getInventoryQty() {
      return inventoryQty_;
    }
    /**
     * <code>uint64 inventory_qty = 2;</code>
     * @param value The inventoryQty to set.
     * @return This builder for chaining.
     */
    public Builder setInventoryQty(long value) {
      
      inventoryQty_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 inventory_qty = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearInventoryQty() {
      
      inventoryQty_ = 0L;
      onChanged();
      return this;
    }

    private long damageQty_ ;
    /**
     * <code>uint64 damage_qty = 3;</code>
     * @return The damageQty.
     */
    @Override
    public long getDamageQty() {
      return damageQty_;
    }
    /**
     * <code>uint64 damage_qty = 3;</code>
     * @param value The damageQty to set.
     * @return This builder for chaining.
     */
    public Builder setDamageQty(long value) {
      
      damageQty_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 damage_qty = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDamageQty() {
      
      damageQty_ = 0L;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:sku.SkuInventoryInfo)
  }

  // @@protoc_insertion_point(class_scope:sku.SkuInventoryInfo)
  private static final SkuInventoryInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new SkuInventoryInfo();
  }

  public static SkuInventoryInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SkuInventoryInfo>
      PARSER = new com.google.protobuf.AbstractParser<SkuInventoryInfo>() {
    @Override
    public SkuInventoryInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SkuInventoryInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SkuInventoryInfo> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<SkuInventoryInfo> getParserForType() {
    return PARSER;
  }

  @Override
  public SkuInventoryInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

