// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/sku.proto

package com.example.wechatmerchant.skurpc;

public interface SkuInventoryReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sku.SkuInventoryReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sku_id = 1;</code>
   * @return The skuId.
   */
  String getSkuId();
  /**
   * <code>string sku_id = 1;</code>
   * @return The bytes for skuId.
   */
  com.google.protobuf.ByteString
      getSkuIdBytes();
}
