// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/sku.proto

package com.example.wechatmerchant.skurpc;

/**
 * Protobuf type {@code sku.SkuInfo}
 */
public final class SkuInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:sku.SkuInfo)
    SkuInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SkuInfo.newBuilder() to construct.
  private SkuInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SkuInfo() {
    skuId_ = "";
    skuName_ = "";
    skuImage_ = "";
    itemName_ = "";
    productName_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new SkuInfo();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SkuInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            skuId_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            skuName_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            skuImage_ = s;
            break;
          }
          case 32: {

            itemId_ = input.readUInt32();
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            itemName_ = s;
            break;
          }
          case 48: {

            productId_ = input.readUInt32();
            break;
          }
          case 58: {
            String s = input.readStringRequireUtf8();

            productName_ = s;
            break;
          }
          case 64: {

            ctime_ = input.readUInt64();
            break;
          }
          case 72: {

            mtime_ = input.readUInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Sku.internal_static_sku_SkuInfo_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Sku.internal_static_sku_SkuInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            SkuInfo.class, Builder.class);
  }

  public static final int SKU_ID_FIELD_NUMBER = 1;
  private volatile Object skuId_;
  /**
   * <code>string sku_id = 1;</code>
   * @return The skuId.
   */
  @Override
  public String getSkuId() {
    Object ref = skuId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      skuId_ = s;
      return s;
    }
  }
  /**
   * <code>string sku_id = 1;</code>
   * @return The bytes for skuId.
   */
  @Override
  public com.google.protobuf.ByteString
      getSkuIdBytes() {
    Object ref = skuId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      skuId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SKU_NAME_FIELD_NUMBER = 2;
  private volatile Object skuName_;
  /**
   * <code>string sku_name = 2;</code>
   * @return The skuName.
   */
  @Override
  public String getSkuName() {
    Object ref = skuName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      skuName_ = s;
      return s;
    }
  }
  /**
   * <code>string sku_name = 2;</code>
   * @return The bytes for skuName.
   */
  @Override
  public com.google.protobuf.ByteString
      getSkuNameBytes() {
    Object ref = skuName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      skuName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SKU_IMAGE_FIELD_NUMBER = 3;
  private volatile Object skuImage_;
  /**
   * <code>string sku_image = 3;</code>
   * @return The skuImage.
   */
  @Override
  public String getSkuImage() {
    Object ref = skuImage_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      skuImage_ = s;
      return s;
    }
  }
  /**
   * <code>string sku_image = 3;</code>
   * @return The bytes for skuImage.
   */
  @Override
  public com.google.protobuf.ByteString
      getSkuImageBytes() {
    Object ref = skuImage_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      skuImage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ITEM_ID_FIELD_NUMBER = 4;
  private int itemId_;
  /**
   * <code>uint32 item_id = 4;</code>
   * @return The itemId.
   */
  @Override
  public int getItemId() {
    return itemId_;
  }

  public static final int ITEM_NAME_FIELD_NUMBER = 5;
  private volatile Object itemName_;
  /**
   * <code>string item_name = 5;</code>
   * @return The itemName.
   */
  @Override
  public String getItemName() {
    Object ref = itemName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      itemName_ = s;
      return s;
    }
  }
  /**
   * <code>string item_name = 5;</code>
   * @return The bytes for itemName.
   */
  @Override
  public com.google.protobuf.ByteString
      getItemNameBytes() {
    Object ref = itemName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      itemName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRODUCT_ID_FIELD_NUMBER = 6;
  private int productId_;
  /**
   * <code>uint32 product_id = 6;</code>
   * @return The productId.
   */
  @Override
  public int getProductId() {
    return productId_;
  }

  public static final int PRODUCT_NAME_FIELD_NUMBER = 7;
  private volatile Object productName_;
  /**
   * <code>string product_name = 7;</code>
   * @return The productName.
   */
  @Override
  public String getProductName() {
    Object ref = productName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      productName_ = s;
      return s;
    }
  }
  /**
   * <code>string product_name = 7;</code>
   * @return The bytes for productName.
   */
  @Override
  public com.google.protobuf.ByteString
      getProductNameBytes() {
    Object ref = productName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      productName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CTIME_FIELD_NUMBER = 8;
  private long ctime_;
  /**
   * <code>uint64 ctime = 8;</code>
   * @return The ctime.
   */
  @Override
  public long getCtime() {
    return ctime_;
  }

  public static final int MTIME_FIELD_NUMBER = 9;
  private long mtime_;
  /**
   * <code>uint64 mtime = 9;</code>
   * @return The mtime.
   */
  @Override
  public long getMtime() {
    return mtime_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(skuId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, skuId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(skuName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, skuName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(skuImage_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, skuImage_);
    }
    if (itemId_ != 0) {
      output.writeUInt32(4, itemId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(itemName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, itemName_);
    }
    if (productId_ != 0) {
      output.writeUInt32(6, productId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, productName_);
    }
    if (ctime_ != 0L) {
      output.writeUInt64(8, ctime_);
    }
    if (mtime_ != 0L) {
      output.writeUInt64(9, mtime_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(skuId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, skuId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(skuName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, skuName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(skuImage_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, skuImage_);
    }
    if (itemId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, itemId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(itemName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, itemName_);
    }
    if (productId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, productId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(productName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, productName_);
    }
    if (ctime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(8, ctime_);
    }
    if (mtime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(9, mtime_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof SkuInfo)) {
      return super.equals(obj);
    }
    SkuInfo other = (SkuInfo) obj;

    if (!getSkuId()
        .equals(other.getSkuId())) return false;
    if (!getSkuName()
        .equals(other.getSkuName())) return false;
    if (!getSkuImage()
        .equals(other.getSkuImage())) return false;
    if (getItemId()
        != other.getItemId()) return false;
    if (!getItemName()
        .equals(other.getItemName())) return false;
    if (getProductId()
        != other.getProductId()) return false;
    if (!getProductName()
        .equals(other.getProductName())) return false;
    if (getCtime()
        != other.getCtime()) return false;
    if (getMtime()
        != other.getMtime()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SKU_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSkuId().hashCode();
    hash = (37 * hash) + SKU_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getSkuName().hashCode();
    hash = (37 * hash) + SKU_IMAGE_FIELD_NUMBER;
    hash = (53 * hash) + getSkuImage().hashCode();
    hash = (37 * hash) + ITEM_ID_FIELD_NUMBER;
    hash = (53 * hash) + getItemId();
    hash = (37 * hash) + ITEM_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getItemName().hashCode();
    hash = (37 * hash) + PRODUCT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getProductId();
    hash = (37 * hash) + PRODUCT_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getProductName().hashCode();
    hash = (37 * hash) + CTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCtime());
    hash = (37 * hash) + MTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMtime());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static SkuInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SkuInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SkuInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SkuInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SkuInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SkuInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SkuInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SkuInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static SkuInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static SkuInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static SkuInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SkuInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(SkuInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code sku.SkuInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sku.SkuInfo)
      SkuInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Sku.internal_static_sku_SkuInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Sku.internal_static_sku_SkuInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SkuInfo.class, Builder.class);
    }

    // Construct using com.example.wechatmerchant.skurpc.SkuInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      skuId_ = "";

      skuName_ = "";

      skuImage_ = "";

      itemId_ = 0;

      itemName_ = "";

      productId_ = 0;

      productName_ = "";

      ctime_ = 0L;

      mtime_ = 0L;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Sku.internal_static_sku_SkuInfo_descriptor;
    }

    @Override
    public SkuInfo getDefaultInstanceForType() {
      return SkuInfo.getDefaultInstance();
    }

    @Override
    public SkuInfo build() {
      SkuInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public SkuInfo buildPartial() {
      SkuInfo result = new SkuInfo(this);
      result.skuId_ = skuId_;
      result.skuName_ = skuName_;
      result.skuImage_ = skuImage_;
      result.itemId_ = itemId_;
      result.itemName_ = itemName_;
      result.productId_ = productId_;
      result.productName_ = productName_;
      result.ctime_ = ctime_;
      result.mtime_ = mtime_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof SkuInfo) {
        return mergeFrom((SkuInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(SkuInfo other) {
      if (other == SkuInfo.getDefaultInstance()) return this;
      if (!other.getSkuId().isEmpty()) {
        skuId_ = other.skuId_;
        onChanged();
      }
      if (!other.getSkuName().isEmpty()) {
        skuName_ = other.skuName_;
        onChanged();
      }
      if (!other.getSkuImage().isEmpty()) {
        skuImage_ = other.skuImage_;
        onChanged();
      }
      if (other.getItemId() != 0) {
        setItemId(other.getItemId());
      }
      if (!other.getItemName().isEmpty()) {
        itemName_ = other.itemName_;
        onChanged();
      }
      if (other.getProductId() != 0) {
        setProductId(other.getProductId());
      }
      if (!other.getProductName().isEmpty()) {
        productName_ = other.productName_;
        onChanged();
      }
      if (other.getCtime() != 0L) {
        setCtime(other.getCtime());
      }
      if (other.getMtime() != 0L) {
        setMtime(other.getMtime());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      SkuInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (SkuInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object skuId_ = "";
    /**
     * <code>string sku_id = 1;</code>
     * @return The skuId.
     */
    public String getSkuId() {
      Object ref = skuId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        skuId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string sku_id = 1;</code>
     * @return The bytes for skuId.
     */
    public com.google.protobuf.ByteString
        getSkuIdBytes() {
      Object ref = skuId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        skuId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sku_id = 1;</code>
     * @param value The skuId to set.
     * @return This builder for chaining.
     */
    public Builder setSkuId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      skuId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sku_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSkuId() {
      
      skuId_ = getDefaultInstance().getSkuId();
      onChanged();
      return this;
    }
    /**
     * <code>string sku_id = 1;</code>
     * @param value The bytes for skuId to set.
     * @return This builder for chaining.
     */
    public Builder setSkuIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      skuId_ = value;
      onChanged();
      return this;
    }

    private Object skuName_ = "";
    /**
     * <code>string sku_name = 2;</code>
     * @return The skuName.
     */
    public String getSkuName() {
      Object ref = skuName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        skuName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string sku_name = 2;</code>
     * @return The bytes for skuName.
     */
    public com.google.protobuf.ByteString
        getSkuNameBytes() {
      Object ref = skuName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        skuName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sku_name = 2;</code>
     * @param value The skuName to set.
     * @return This builder for chaining.
     */
    public Builder setSkuName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      skuName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sku_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSkuName() {
      
      skuName_ = getDefaultInstance().getSkuName();
      onChanged();
      return this;
    }
    /**
     * <code>string sku_name = 2;</code>
     * @param value The bytes for skuName to set.
     * @return This builder for chaining.
     */
    public Builder setSkuNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      skuName_ = value;
      onChanged();
      return this;
    }

    private Object skuImage_ = "";
    /**
     * <code>string sku_image = 3;</code>
     * @return The skuImage.
     */
    public String getSkuImage() {
      Object ref = skuImage_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        skuImage_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string sku_image = 3;</code>
     * @return The bytes for skuImage.
     */
    public com.google.protobuf.ByteString
        getSkuImageBytes() {
      Object ref = skuImage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        skuImage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sku_image = 3;</code>
     * @param value The skuImage to set.
     * @return This builder for chaining.
     */
    public Builder setSkuImage(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      skuImage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sku_image = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSkuImage() {
      
      skuImage_ = getDefaultInstance().getSkuImage();
      onChanged();
      return this;
    }
    /**
     * <code>string sku_image = 3;</code>
     * @param value The bytes for skuImage to set.
     * @return This builder for chaining.
     */
    public Builder setSkuImageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      skuImage_ = value;
      onChanged();
      return this;
    }

    private int itemId_ ;
    /**
     * <code>uint32 item_id = 4;</code>
     * @return The itemId.
     */
    @Override
    public int getItemId() {
      return itemId_;
    }
    /**
     * <code>uint32 item_id = 4;</code>
     * @param value The itemId to set.
     * @return This builder for chaining.
     */
    public Builder setItemId(int value) {
      
      itemId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 item_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearItemId() {
      
      itemId_ = 0;
      onChanged();
      return this;
    }

    private Object itemName_ = "";
    /**
     * <code>string item_name = 5;</code>
     * @return The itemName.
     */
    public String getItemName() {
      Object ref = itemName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        itemName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string item_name = 5;</code>
     * @return The bytes for itemName.
     */
    public com.google.protobuf.ByteString
        getItemNameBytes() {
      Object ref = itemName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        itemName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string item_name = 5;</code>
     * @param value The itemName to set.
     * @return This builder for chaining.
     */
    public Builder setItemName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      itemName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string item_name = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearItemName() {
      
      itemName_ = getDefaultInstance().getItemName();
      onChanged();
      return this;
    }
    /**
     * <code>string item_name = 5;</code>
     * @param value The bytes for itemName to set.
     * @return This builder for chaining.
     */
    public Builder setItemNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      itemName_ = value;
      onChanged();
      return this;
    }

    private int productId_ ;
    /**
     * <code>uint32 product_id = 6;</code>
     * @return The productId.
     */
    @Override
    public int getProductId() {
      return productId_;
    }
    /**
     * <code>uint32 product_id = 6;</code>
     * @param value The productId to set.
     * @return This builder for chaining.
     */
    public Builder setProductId(int value) {
      
      productId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 product_id = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductId() {
      
      productId_ = 0;
      onChanged();
      return this;
    }

    private Object productName_ = "";
    /**
     * <code>string product_name = 7;</code>
     * @return The productName.
     */
    public String getProductName() {
      Object ref = productName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        productName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string product_name = 7;</code>
     * @return The bytes for productName.
     */
    public com.google.protobuf.ByteString
        getProductNameBytes() {
      Object ref = productName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        productName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string product_name = 7;</code>
     * @param value The productName to set.
     * @return This builder for chaining.
     */
    public Builder setProductName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      productName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string product_name = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductName() {
      
      productName_ = getDefaultInstance().getProductName();
      onChanged();
      return this;
    }
    /**
     * <code>string product_name = 7;</code>
     * @param value The bytes for productName to set.
     * @return This builder for chaining.
     */
    public Builder setProductNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      productName_ = value;
      onChanged();
      return this;
    }

    private long ctime_ ;
    /**
     * <code>uint64 ctime = 8;</code>
     * @return The ctime.
     */
    @Override
    public long getCtime() {
      return ctime_;
    }
    /**
     * <code>uint64 ctime = 8;</code>
     * @param value The ctime to set.
     * @return This builder for chaining.
     */
    public Builder setCtime(long value) {
      
      ctime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 ctime = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearCtime() {
      
      ctime_ = 0L;
      onChanged();
      return this;
    }

    private long mtime_ ;
    /**
     * <code>uint64 mtime = 9;</code>
     * @return The mtime.
     */
    @Override
    public long getMtime() {
      return mtime_;
    }
    /**
     * <code>uint64 mtime = 9;</code>
     * @param value The mtime to set.
     * @return This builder for chaining.
     */
    public Builder setMtime(long value) {
      
      mtime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 mtime = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearMtime() {
      
      mtime_ = 0L;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:sku.SkuInfo)
  }

  // @@protoc_insertion_point(class_scope:sku.SkuInfo)
  private static final SkuInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new SkuInfo();
  }

  public static SkuInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SkuInfo>
      PARSER = new com.google.protobuf.AbstractParser<SkuInfo>() {
    @Override
    public SkuInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SkuInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SkuInfo> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<SkuInfo> getParserForType() {
    return PARSER;
  }

  @Override
  public SkuInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

