// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/sku.proto

package com.example.wechatmerchant.skurpc;

public interface SkuInventoryInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sku.SkuInventoryInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sku_id = 1;</code>
   * @return The skuId.
   */
  String getSkuId();
  /**
   * <code>string sku_id = 1;</code>
   * @return The bytes for skuId.
   */
  com.google.protobuf.ByteString
      getSkuIdBytes();

  /**
   * <code>uint64 inventory_qty = 2;</code>
   * @return The inventoryQty.
   */
  long getInventoryQty();

  /**
   * <code>uint64 damage_qty = 3;</code>
   * @return The damageQty.
   */
  long getDamageQty();
}
