// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/sku.proto

package com.example.wechatmerchant.skurpc;

/**
 * Protobuf type {@code sku.SkuInventoryReq}
 */
public final class SkuInventoryReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:sku.SkuInventoryReq)
    SkuInventoryReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SkuInventoryReq.newBuilder() to construct.
  private SkuInventoryReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SkuInventoryReq() {
    skuId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SkuInventoryReq();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SkuInventoryReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              skuId_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            skuId_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        skuId_ = skuId_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.wechatmerchant.skurpc.Sku.internal_static_sku_SkuInventoryReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.wechatmerchant.skurpc.Sku.internal_static_sku_SkuInventoryReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.wechatmerchant.skurpc.SkuInventoryReq.class, com.example.wechatmerchant.skurpc.SkuInventoryReq.Builder.class);
  }

  public static final int SKU_ID_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList skuId_;
  /**
   * <code>repeated string sku_id = 1;</code>
   * @return A list containing the skuId.
   */
  public com.google.protobuf.ProtocolStringList
      getSkuIdList() {
    return skuId_;
  }
  /**
   * <code>repeated string sku_id = 1;</code>
   * @return The count of skuId.
   */
  public int getSkuIdCount() {
    return skuId_.size();
  }
  /**
   * <code>repeated string sku_id = 1;</code>
   * @param index The index of the element to return.
   * @return The skuId at the given index.
   */
  public java.lang.String getSkuId(int index) {
    return skuId_.get(index);
  }
  /**
   * <code>repeated string sku_id = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the skuId at the given index.
   */
  public com.google.protobuf.ByteString
      getSkuIdBytes(int index) {
    return skuId_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < skuId_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, skuId_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < skuId_.size(); i++) {
        dataSize += computeStringSizeNoTag(skuId_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getSkuIdList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.wechatmerchant.skurpc.SkuInventoryReq)) {
      return super.equals(obj);
    }
    com.example.wechatmerchant.skurpc.SkuInventoryReq other = (com.example.wechatmerchant.skurpc.SkuInventoryReq) obj;

    if (!getSkuIdList()
        .equals(other.getSkuIdList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getSkuIdCount() > 0) {
      hash = (37 * hash) + SKU_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSkuIdList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.wechatmerchant.skurpc.SkuInventoryReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.wechatmerchant.skurpc.SkuInventoryReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.wechatmerchant.skurpc.SkuInventoryReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.wechatmerchant.skurpc.SkuInventoryReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.wechatmerchant.skurpc.SkuInventoryReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.wechatmerchant.skurpc.SkuInventoryReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.wechatmerchant.skurpc.SkuInventoryReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.wechatmerchant.skurpc.SkuInventoryReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.wechatmerchant.skurpc.SkuInventoryReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.wechatmerchant.skurpc.SkuInventoryReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.wechatmerchant.skurpc.SkuInventoryReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.wechatmerchant.skurpc.SkuInventoryReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.wechatmerchant.skurpc.SkuInventoryReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code sku.SkuInventoryReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sku.SkuInventoryReq)
      com.example.wechatmerchant.skurpc.SkuInventoryReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.wechatmerchant.skurpc.Sku.internal_static_sku_SkuInventoryReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.wechatmerchant.skurpc.Sku.internal_static_sku_SkuInventoryReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.wechatmerchant.skurpc.SkuInventoryReq.class, com.example.wechatmerchant.skurpc.SkuInventoryReq.Builder.class);
    }

    // Construct using com.example.wechatmerchant.skurpc.SkuInventoryReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      skuId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.wechatmerchant.skurpc.Sku.internal_static_sku_SkuInventoryReq_descriptor;
    }

    @java.lang.Override
    public com.example.wechatmerchant.skurpc.SkuInventoryReq getDefaultInstanceForType() {
      return com.example.wechatmerchant.skurpc.SkuInventoryReq.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.wechatmerchant.skurpc.SkuInventoryReq build() {
      com.example.wechatmerchant.skurpc.SkuInventoryReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.wechatmerchant.skurpc.SkuInventoryReq buildPartial() {
      com.example.wechatmerchant.skurpc.SkuInventoryReq result = new com.example.wechatmerchant.skurpc.SkuInventoryReq(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        skuId_ = skuId_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.skuId_ = skuId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.wechatmerchant.skurpc.SkuInventoryReq) {
        return mergeFrom((com.example.wechatmerchant.skurpc.SkuInventoryReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.wechatmerchant.skurpc.SkuInventoryReq other) {
      if (other == com.example.wechatmerchant.skurpc.SkuInventoryReq.getDefaultInstance()) return this;
      if (!other.skuId_.isEmpty()) {
        if (skuId_.isEmpty()) {
          skuId_ = other.skuId_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureSkuIdIsMutable();
          skuId_.addAll(other.skuId_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.wechatmerchant.skurpc.SkuInventoryReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.wechatmerchant.skurpc.SkuInventoryReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList skuId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureSkuIdIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        skuId_ = new com.google.protobuf.LazyStringArrayList(skuId_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string sku_id = 1;</code>
     * @return A list containing the skuId.
     */
    public com.google.protobuf.ProtocolStringList
        getSkuIdList() {
      return skuId_.getUnmodifiableView();
    }
    /**
     * <code>repeated string sku_id = 1;</code>
     * @return The count of skuId.
     */
    public int getSkuIdCount() {
      return skuId_.size();
    }
    /**
     * <code>repeated string sku_id = 1;</code>
     * @param index The index of the element to return.
     * @return The skuId at the given index.
     */
    public java.lang.String getSkuId(int index) {
      return skuId_.get(index);
    }
    /**
     * <code>repeated string sku_id = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the skuId at the given index.
     */
    public com.google.protobuf.ByteString
        getSkuIdBytes(int index) {
      return skuId_.getByteString(index);
    }
    /**
     * <code>repeated string sku_id = 1;</code>
     * @param index The index to set the value at.
     * @param value The skuId to set.
     * @return This builder for chaining.
     */
    public Builder setSkuId(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureSkuIdIsMutable();
      skuId_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string sku_id = 1;</code>
     * @param value The skuId to add.
     * @return This builder for chaining.
     */
    public Builder addSkuId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureSkuIdIsMutable();
      skuId_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string sku_id = 1;</code>
     * @param values The skuId to add.
     * @return This builder for chaining.
     */
    public Builder addAllSkuId(
        java.lang.Iterable<java.lang.String> values) {
      ensureSkuIdIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, skuId_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string sku_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSkuId() {
      skuId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string sku_id = 1;</code>
     * @param value The bytes of the skuId to add.
     * @return This builder for chaining.
     */
    public Builder addSkuIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureSkuIdIsMutable();
      skuId_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:sku.SkuInventoryReq)
  }

  // @@protoc_insertion_point(class_scope:sku.SkuInventoryReq)
  private static final com.example.wechatmerchant.skurpc.SkuInventoryReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.wechatmerchant.skurpc.SkuInventoryReq();
  }

  public static com.example.wechatmerchant.skurpc.SkuInventoryReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SkuInventoryReq>
      PARSER = new com.google.protobuf.AbstractParser<SkuInventoryReq>() {
    @java.lang.Override
    public SkuInventoryReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SkuInventoryReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SkuInventoryReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SkuInventoryReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.wechatmerchant.skurpc.SkuInventoryReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

