// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/sku.proto

// Protobuf Java Version: 3.25.3
package com.example.wechatmerchant.skurpc;

public interface SkuInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sku.SkuInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sku_id = 1;</code>
   * @return The skuId.
   */
  java.lang.String getSkuId();
  /**
   * <code>string sku_id = 1;</code>
   * @return The bytes for skuId.
   */
  com.google.protobuf.ByteString
      getSkuIdBytes();

  /**
   * <code>string sku_name = 2;</code>
   * @return The skuName.
   */
  java.lang.String getSkuName();
  /**
   * <code>string sku_name = 2;</code>
   * @return The bytes for skuName.
   */
  com.google.protobuf.ByteString
      getSkuNameBytes();

  /**
   * <code>string sku_image = 3;</code>
   * @return The skuImage.
   */
  java.lang.String getSkuImage();
  /**
   * <code>string sku_image = 3;</code>
   * @return The bytes for skuImage.
   */
  com.google.protobuf.ByteString
      getSkuImageBytes();

  /**
   * <code>uint32 item_id = 4;</code>
   * @return The itemId.
   */
  int getItemId();

  /**
   * <code>string item_name = 5;</code>
   * @return The itemName.
   */
  java.lang.String getItemName();
  /**
   * <code>string item_name = 5;</code>
   * @return The bytes for itemName.
   */
  com.google.protobuf.ByteString
      getItemNameBytes();

  /**
   * <code>uint32 product_id = 6;</code>
   * @return The productId.
   */
  int getProductId();

  /**
   * <code>string product_name = 7;</code>
   * @return The productName.
   */
  java.lang.String getProductName();
  /**
   * <code>string product_name = 7;</code>
   * @return The bytes for productName.
   */
  com.google.protobuf.ByteString
      getProductNameBytes();

  /**
   * <code>uint32 ctime = 8;</code>
   * @return The ctime.
   */
  int getCtime();

  /**
   * <code>uint32 mtime = 9;</code>
   * @return The mtime.
   */
  int getMtime();
}
