// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/sku.proto

package com.example.wechatmerchant.skurpc;

public interface SkuInventoryRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sku.SkuInventoryResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.sku.CommonRsp common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.sku.CommonRsp common = 1;</code>
   * @return The common.
   */
  CommonRsp getCommon();
  /**
   * <code>.sku.CommonRsp common = 1;</code>
   */
  CommonRspOrBuilder getCommonOrBuilder();

  /**
   * <code>repeated .sku.SkuInventoryInfo data = 2;</code>
   */
  java.util.List<SkuInventoryInfo>
      getDataList();
  /**
   * <code>repeated .sku.SkuInventoryInfo data = 2;</code>
   */
  SkuInventoryInfo getData(int index);
  /**
   * <code>repeated .sku.SkuInventoryInfo data = 2;</code>
   */
  int getDataCount();
  /**
   * <code>repeated .sku.SkuInventoryInfo data = 2;</code>
   */
  java.util.List<? extends SkuInventoryInfoOrBuilder>
      getDataOrBuilderList();
  /**
   * <code>repeated .sku.SkuInventoryInfo data = 2;</code>
   */
  SkuInventoryInfoOrBuilder getDataOrBuilder(
      int index);
}
