// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/sku.proto

package com.example.wechatmerchant.skurpc;

/**
 * Protobuf type {@code sku.SkuReq}
 */
public final class SkuReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:sku.SkuReq)
    SkuReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SkuReq.newBuilder() to construct.
  private SkuReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SkuReq() {
    skuId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new SkuReq();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SkuReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              skuId_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            skuId_.add(s);
            break;
          }
          case 16: {

            pageNumber_ = input.readUInt64();
            break;
          }
          case 24: {

            pageSize_ = input.readUInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        skuId_ = skuId_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Sku.internal_static_sku_SkuReq_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Sku.internal_static_sku_SkuReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            SkuReq.class, Builder.class);
  }

  public static final int SKU_ID_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList skuId_;
  /**
   * <code>repeated string sku_id = 1;</code>
   * @return A list containing the skuId.
   */
  public com.google.protobuf.ProtocolStringList
      getSkuIdList() {
    return skuId_;
  }
  /**
   * <code>repeated string sku_id = 1;</code>
   * @return The count of skuId.
   */
  public int getSkuIdCount() {
    return skuId_.size();
  }
  /**
   * <code>repeated string sku_id = 1;</code>
   * @param index The index of the element to return.
   * @return The skuId at the given index.
   */
  public String getSkuId(int index) {
    return skuId_.get(index);
  }
  /**
   * <code>repeated string sku_id = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the skuId at the given index.
   */
  public com.google.protobuf.ByteString
      getSkuIdBytes(int index) {
    return skuId_.getByteString(index);
  }

  public static final int PAGE_NUMBER_FIELD_NUMBER = 2;
  private long pageNumber_;
  /**
   * <code>uint64 page_number = 2;</code>
   * @return The pageNumber.
   */
  @Override
  public long getPageNumber() {
    return pageNumber_;
  }

  public static final int PAGE_SIZE_FIELD_NUMBER = 3;
  private long pageSize_;
  /**
   * <code>uint64 page_size = 3;</code>
   * @return The pageSize.
   */
  @Override
  public long getPageSize() {
    return pageSize_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < skuId_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, skuId_.getRaw(i));
    }
    if (pageNumber_ != 0L) {
      output.writeUInt64(2, pageNumber_);
    }
    if (pageSize_ != 0L) {
      output.writeUInt64(3, pageSize_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < skuId_.size(); i++) {
        dataSize += computeStringSizeNoTag(skuId_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getSkuIdList().size();
    }
    if (pageNumber_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, pageNumber_);
    }
    if (pageSize_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, pageSize_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof SkuReq)) {
      return super.equals(obj);
    }
    SkuReq other = (SkuReq) obj;

    if (!getSkuIdList()
        .equals(other.getSkuIdList())) return false;
    if (getPageNumber()
        != other.getPageNumber()) return false;
    if (getPageSize()
        != other.getPageSize()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getSkuIdCount() > 0) {
      hash = (37 * hash) + SKU_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSkuIdList().hashCode();
    }
    hash = (37 * hash) + PAGE_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPageNumber());
    hash = (37 * hash) + PAGE_SIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPageSize());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static SkuReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SkuReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SkuReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SkuReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SkuReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SkuReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SkuReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SkuReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static SkuReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static SkuReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static SkuReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SkuReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(SkuReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code sku.SkuReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sku.SkuReq)
      SkuReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Sku.internal_static_sku_SkuReq_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Sku.internal_static_sku_SkuReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SkuReq.class, Builder.class);
    }

    // Construct using com.example.wechatmerchant.skurpc.SkuReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      skuId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      pageNumber_ = 0L;

      pageSize_ = 0L;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Sku.internal_static_sku_SkuReq_descriptor;
    }

    @Override
    public SkuReq getDefaultInstanceForType() {
      return SkuReq.getDefaultInstance();
    }

    @Override
    public SkuReq build() {
      SkuReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public SkuReq buildPartial() {
      SkuReq result = new SkuReq(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        skuId_ = skuId_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.skuId_ = skuId_;
      result.pageNumber_ = pageNumber_;
      result.pageSize_ = pageSize_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof SkuReq) {
        return mergeFrom((SkuReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(SkuReq other) {
      if (other == SkuReq.getDefaultInstance()) return this;
      if (!other.skuId_.isEmpty()) {
        if (skuId_.isEmpty()) {
          skuId_ = other.skuId_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureSkuIdIsMutable();
          skuId_.addAll(other.skuId_);
        }
        onChanged();
      }
      if (other.getPageNumber() != 0L) {
        setPageNumber(other.getPageNumber());
      }
      if (other.getPageSize() != 0L) {
        setPageSize(other.getPageSize());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      SkuReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (SkuReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList skuId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureSkuIdIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        skuId_ = new com.google.protobuf.LazyStringArrayList(skuId_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string sku_id = 1;</code>
     * @return A list containing the skuId.
     */
    public com.google.protobuf.ProtocolStringList
        getSkuIdList() {
      return skuId_.getUnmodifiableView();
    }
    /**
     * <code>repeated string sku_id = 1;</code>
     * @return The count of skuId.
     */
    public int getSkuIdCount() {
      return skuId_.size();
    }
    /**
     * <code>repeated string sku_id = 1;</code>
     * @param index The index of the element to return.
     * @return The skuId at the given index.
     */
    public String getSkuId(int index) {
      return skuId_.get(index);
    }
    /**
     * <code>repeated string sku_id = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the skuId at the given index.
     */
    public com.google.protobuf.ByteString
        getSkuIdBytes(int index) {
      return skuId_.getByteString(index);
    }
    /**
     * <code>repeated string sku_id = 1;</code>
     * @param index The index to set the value at.
     * @param value The skuId to set.
     * @return This builder for chaining.
     */
    public Builder setSkuId(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureSkuIdIsMutable();
      skuId_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string sku_id = 1;</code>
     * @param value The skuId to add.
     * @return This builder for chaining.
     */
    public Builder addSkuId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureSkuIdIsMutable();
      skuId_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string sku_id = 1;</code>
     * @param values The skuId to add.
     * @return This builder for chaining.
     */
    public Builder addAllSkuId(
        Iterable<String> values) {
      ensureSkuIdIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, skuId_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string sku_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSkuId() {
      skuId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string sku_id = 1;</code>
     * @param value The bytes of the skuId to add.
     * @return This builder for chaining.
     */
    public Builder addSkuIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureSkuIdIsMutable();
      skuId_.add(value);
      onChanged();
      return this;
    }

    private long pageNumber_ ;
    /**
     * <code>uint64 page_number = 2;</code>
     * @return The pageNumber.
     */
    @Override
    public long getPageNumber() {
      return pageNumber_;
    }
    /**
     * <code>uint64 page_number = 2;</code>
     * @param value The pageNumber to set.
     * @return This builder for chaining.
     */
    public Builder setPageNumber(long value) {
      
      pageNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 page_number = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPageNumber() {
      
      pageNumber_ = 0L;
      onChanged();
      return this;
    }

    private long pageSize_ ;
    /**
     * <code>uint64 page_size = 3;</code>
     * @return The pageSize.
     */
    @Override
    public long getPageSize() {
      return pageSize_;
    }
    /**
     * <code>uint64 page_size = 3;</code>
     * @param value The pageSize to set.
     * @return This builder for chaining.
     */
    public Builder setPageSize(long value) {
      
      pageSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 page_size = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPageSize() {
      
      pageSize_ = 0L;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:sku.SkuReq)
  }

  // @@protoc_insertion_point(class_scope:sku.SkuReq)
  private static final SkuReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new SkuReq();
  }

  public static SkuReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SkuReq>
      PARSER = new com.google.protobuf.AbstractParser<SkuReq>() {
    @Override
    public SkuReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SkuReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SkuReq> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<SkuReq> getParserForType() {
    return PARSER;
  }

  @Override
  public SkuReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

