// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/sku.proto

// Protobuf Java Version: 3.25.3
package com.example.wechatmerchant.skurpc;

/**
 * Protobuf type {@code sku.UpdateSkuInventoryInfoReq}
 */
public final class UpdateSkuInventoryInfoReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:sku.UpdateSkuInventoryInfoReq)
    UpdateSkuInventoryInfoReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UpdateSkuInventoryInfoReq.newBuilder() to construct.
  private UpdateSkuInventoryInfoReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateSkuInventoryInfoReq() {
    skuId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UpdateSkuInventoryInfoReq();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.wechatmerchant.skurpc.Sku.internal_static_sku_UpdateSkuInventoryInfoReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.wechatmerchant.skurpc.Sku.internal_static_sku_UpdateSkuInventoryInfoReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq.class, com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq.Builder.class);
  }

  public static final int SKU_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object skuId_ = "";
  /**
   * <code>string sku_id = 1;</code>
   * @return The skuId.
   */
  @java.lang.Override
  public java.lang.String getSkuId() {
    java.lang.Object ref = skuId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      skuId_ = s;
      return s;
    }
  }
  /**
   * <code>string sku_id = 1;</code>
   * @return The bytes for skuId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSkuIdBytes() {
    java.lang.Object ref = skuId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      skuId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INVENTORY_QTY_FIELD_NUMBER = 2;
  private int inventoryQty_ = 0;
  /**
   * <code>uint32 inventory_qty = 2;</code>
   * @return The inventoryQty.
   */
  @java.lang.Override
  public int getInventoryQty() {
    return inventoryQty_;
  }

  public static final int DAMAGE_QTY_FIELD_NUMBER = 3;
  private int damageQty_ = 0;
  /**
   * <code>uint32 damage_qty = 3;</code>
   * @return The damageQty.
   */
  @java.lang.Override
  public int getDamageQty() {
    return damageQty_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(skuId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, skuId_);
    }
    if (inventoryQty_ != 0) {
      output.writeUInt32(2, inventoryQty_);
    }
    if (damageQty_ != 0) {
      output.writeUInt32(3, damageQty_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(skuId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, skuId_);
    }
    if (inventoryQty_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, inventoryQty_);
    }
    if (damageQty_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, damageQty_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq)) {
      return super.equals(obj);
    }
    com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq other = (com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq) obj;

    if (!getSkuId()
        .equals(other.getSkuId())) return false;
    if (getInventoryQty()
        != other.getInventoryQty()) return false;
    if (getDamageQty()
        != other.getDamageQty()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SKU_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSkuId().hashCode();
    hash = (37 * hash) + INVENTORY_QTY_FIELD_NUMBER;
    hash = (53 * hash) + getInventoryQty();
    hash = (37 * hash) + DAMAGE_QTY_FIELD_NUMBER;
    hash = (53 * hash) + getDamageQty();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code sku.UpdateSkuInventoryInfoReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sku.UpdateSkuInventoryInfoReq)
      com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.wechatmerchant.skurpc.Sku.internal_static_sku_UpdateSkuInventoryInfoReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.wechatmerchant.skurpc.Sku.internal_static_sku_UpdateSkuInventoryInfoReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq.class, com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq.Builder.class);
    }

    // Construct using com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      skuId_ = "";
      inventoryQty_ = 0;
      damageQty_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.wechatmerchant.skurpc.Sku.internal_static_sku_UpdateSkuInventoryInfoReq_descriptor;
    }

    @java.lang.Override
    public com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq getDefaultInstanceForType() {
      return com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq build() {
      com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq buildPartial() {
      com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq result = new com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.skuId_ = skuId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.inventoryQty_ = inventoryQty_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.damageQty_ = damageQty_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq) {
        return mergeFrom((com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq other) {
      if (other == com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq.getDefaultInstance()) return this;
      if (!other.getSkuId().isEmpty()) {
        skuId_ = other.skuId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getInventoryQty() != 0) {
        setInventoryQty(other.getInventoryQty());
      }
      if (other.getDamageQty() != 0) {
        setDamageQty(other.getDamageQty());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              skuId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              inventoryQty_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              damageQty_ = input.readUInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object skuId_ = "";
    /**
     * <code>string sku_id = 1;</code>
     * @return The skuId.
     */
    public java.lang.String getSkuId() {
      java.lang.Object ref = skuId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        skuId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sku_id = 1;</code>
     * @return The bytes for skuId.
     */
    public com.google.protobuf.ByteString
        getSkuIdBytes() {
      java.lang.Object ref = skuId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        skuId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sku_id = 1;</code>
     * @param value The skuId to set.
     * @return This builder for chaining.
     */
    public Builder setSkuId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      skuId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string sku_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSkuId() {
      skuId_ = getDefaultInstance().getSkuId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string sku_id = 1;</code>
     * @param value The bytes for skuId to set.
     * @return This builder for chaining.
     */
    public Builder setSkuIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      skuId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int inventoryQty_ ;
    /**
     * <code>uint32 inventory_qty = 2;</code>
     * @return The inventoryQty.
     */
    @java.lang.Override
    public int getInventoryQty() {
      return inventoryQty_;
    }
    /**
     * <code>uint32 inventory_qty = 2;</code>
     * @param value The inventoryQty to set.
     * @return This builder for chaining.
     */
    public Builder setInventoryQty(int value) {

      inventoryQty_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 inventory_qty = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearInventoryQty() {
      bitField0_ = (bitField0_ & ~0x00000002);
      inventoryQty_ = 0;
      onChanged();
      return this;
    }

    private int damageQty_ ;
    /**
     * <code>uint32 damage_qty = 3;</code>
     * @return The damageQty.
     */
    @java.lang.Override
    public int getDamageQty() {
      return damageQty_;
    }
    /**
     * <code>uint32 damage_qty = 3;</code>
     * @param value The damageQty to set.
     * @return This builder for chaining.
     */
    public Builder setDamageQty(int value) {

      damageQty_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 damage_qty = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDamageQty() {
      bitField0_ = (bitField0_ & ~0x00000004);
      damageQty_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:sku.UpdateSkuInventoryInfoReq)
  }

  // @@protoc_insertion_point(class_scope:sku.UpdateSkuInventoryInfoReq)
  private static final com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq();
  }

  public static com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateSkuInventoryInfoReq>
      PARSER = new com.google.protobuf.AbstractParser<UpdateSkuInventoryInfoReq>() {
    @java.lang.Override
    public UpdateSkuInventoryInfoReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UpdateSkuInventoryInfoReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateSkuInventoryInfoReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.wechatmerchant.skurpc.UpdateSkuInventoryInfoReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

